# Generated by Django 4.0.4 on 2022-05-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorId', models.CharField(max_length=100)),
                ('authorResidence', models.CharField(max_length=100)),
                ('communtId', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('contentId', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('timestamp', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communityId', models.UUIDField()),
                ('highQuality', models.FloatField()),
                ('content', models.TextField()),
                ('pattern', models.FloatField()),
                ('popularity', models.FloatField()),
                ('random', models.FloatField()),
                ('timelines', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('eventType', models.IntegerField(unique=True)),
                ('communityId', models.CharField(max_length=100)),
                ('source', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleRecommender.article')),
            ],
        ),
    ]
