# Generated by Django 4.0.4 on 2022-05-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleRecommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authorId',
            field=models.CharField(max_length=100),
        ),
    ]
