# Generated by Django 4.0.4 on 2022-05-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleRecommender', '0002_alter_article_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='communtId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='contentId',
            field=models.CharField(max_length=100),
        ),
    ]
